# Generated by Django 3.2.3 on 2021-11-14 20:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('v1_courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='useroncourse',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usercoursestatus',
            name='user_on_course',
            field=models.ManyToManyField(to='v1_courses.UserOnCourse'),
        ),
    ]
