# Generated by Django 3.2.6 on 2021-12-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_courses', '0003_alter_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='useroncourse',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='useroncourse',
            name='status',
            field=models.IntegerField(choices=[(1, 'listener'), (2, 'passed'), (3, 'curator'), (4, 'archived'), (5, 'admin')], default=1),
        ),
        migrations.DeleteModel(
            name='UserCourseStatus',
        ),
    ]
