# Generated by Django 3.2.6 on 2021-12-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_courses', '0004_auto_20211209_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useroncourse',
            name='status',
            field=models.IntegerField(choices=[(1, 'listener'), (2, 'passed'), (3, 'archived'), (4, 'curator'), (5, 'admin')], default=1),
        ),
    ]
