# Generated by Django 3.1.3 on 2022-02-14 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1_courses', '0006_alter_useroncourse_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useroncourse',
            old_name='status',
            new_name='user_status',
        ),
    ]
