# Generated by Django 3.1.3 on 2022-03-21 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('v1_courses', '0008_auto_20220224_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useroncourse',
            name='user',
        ),
        migrations.AddField(
            model_name='useroncourse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1_users.user'),
            preserve_default=False,
        ),
    ]
