# Generated by Django 3.1.3 on 2022-04-04 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1_courses', '0009_auto_20220321_2155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterModelOptions(
            name='useroncourse',
            options={'verbose_name_plural': 'Пользователь на курсе'},
        ),
    ]
