# Generated by Django 3.1.3 on 2022-04-04 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1_courses', '0010_auto_20220404_2307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useroncourse',
            options={'verbose_name_plural': 'Слушатели'},
        ),
    ]
