# Generated by Django 3.1.3 on 2022-04-04 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('v1_courses', '0013_auto_20220405_0037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useroncourse',
            options={'verbose_name': 'Слушатель', 'verbose_name_plural': ('Слушатели',)},
        ),
        migrations.AlterField(
            model_name='useroncourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1_courses.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='useroncourse',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='useroncourse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='useroncourse',
            name='user_status',
            field=models.IntegerField(choices=[(1, 'слушатель'), (2, 'куратор'), (3, 'администратор')], default=1, verbose_name='Статус'),
        ),
    ]
