# Generated by Django 3.1.3 on 2022-04-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_courses', '0014_auto_20220405_0046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useroncourse',
            options={'verbose_name': 'Слушатель', 'verbose_name_plural': 'Слушатели'},
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.IntegerField(choices=[(1, 'open'), (2, 'closed'), (3, 'available')], default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='useroncourse',
            name='user_status',
            field=models.IntegerField(choices=[(1, 'listener'), (2, 'curator'), (3, 'admin')], default=1, verbose_name='Статус'),
        ),
    ]
