# Generated by Django 3.1.3 on 2022-04-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_courses', '0015_auto_20220413_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.IntegerField(choices=[(1, 'open'), (2, 'closed'), (3, 'available')], default=2, verbose_name='Статус'),
        ),
    ]
