# Generated by Django 3.1.3 on 2022-05-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_courses', '0016_auto_20220413_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='english_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название на английском'),
        ),
    ]
