# Generated by Django 3.1.3 on 2022-05-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_courses', '0017_course_english_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='english_name',
            field=models.CharField(max_length=100, verbose_name='Название на английском'),
        ),
    ]
