# Generated by Django 3.1.3 on 2022-05-10 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1_courses', '0018_auto_20220502_1201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useroncourse',
            options={'permissions': (('curator', 'Куратор курса'),), 'verbose_name': 'Слушатель', 'verbose_name_plural': 'Слушатели'},
        ),
    ]
