# Generated by Django 3.1.3 on 2022-05-10 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1_courses', '0020_auto_20220510_1346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useroncourse',
            options={'verbose_name': 'Слушатель', 'verbose_name_plural': 'Слушатели'},
        ),
    ]
