version: '3.3'

services:
  web:
    container_name: web
    build:
      context: ..
      dockerfile: ./env/Dockerfile
    restart: on-failure
    expose:
      - 8000
    env_file:
      - prod.env
    depends_on:
      - db
    volumes:
      - ../:/srv/html/djangoTask
    command: sh -c "gunicorn -c env/gunicorn.py djangoTask.asgi:application"

  db:
    image: postgres:12
    restart: on-failure
    env_file:
      - prod.env
    expose:
      - 5432
    volumes:
      - db_volume:/var/lib/postgres/data/pgdata

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.prod.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - ../static:/static
      - ../media:/media
    depends_on:
      - web
    ports:
      - 80:80
      - 443:443

volumes:
  db_volume:
