# Generated by Django 3.1.3 on 2022-04-25 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1_courses', '0016_auto_20220413_1534'),
        ('v1_reviews', '0004_auto_20220413_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='course',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to='v1_courses.course', verbose_name='Курс'),
            preserve_default=False,
        ),
    ]
