# Generated by Django 3.1.3 on 2022-03-16 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1_lessons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='task_points',
            new_name='task_max_points',
        ),
    ]
