# Generated by Django 3.1.3 on 2022-03-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_courses', '0008_auto_20220224_2011'),
        ('v1_lessons', '0002_auto_20220316_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ManyToManyField(to='v1_courses.Course'),
        ),
    ]
