# Generated by Django 3.1.3 on 2022-03-17 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1_lessons', '0003_lesson_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='task_max_points',
        ),
    ]
