# Generated by Django 3.1.3 on 2022-03-20 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_courses', '0008_auto_20220224_2011'),
        ('v1_lessons', '0005_lesson_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, to='v1_courses.UserOnCourse'),
        ),
    ]
