# Generated by Django 3.1.3 on 2022-03-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_lessons', '0006_auto_20220321_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='status',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='user',
        ),
        migrations.AddField(
            model_name='lesson',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
