# Generated by Django 3.1.3 on 2022-03-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_courses', '0009_auto_20220321_2155'),
        ('v1_lessons', '0007_auto_20220321_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='viewed_by',
            field=models.ManyToManyField(to='v1_courses.UserOnCourse'),
        ),
    ]
