# Generated by Django 3.1.3 on 2022-03-23 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1_lessons', '0008_lesson_viewed_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='viewed_by',
        ),
    ]
