# Generated by Django 3.1.3 on 2022-03-31 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1_courses', '0009_auto_20220321_2155'),
        ('v1_lessons', '0009_remove_lesson_viewed_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='course',
        ),
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1_courses.course'),
            preserve_default=False,
        ),
    ]
