# Generated by Django 3.1.3 on 2022-04-04 20:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1_lessons', '0010_auto_20220331_2000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name_plural': 'Уроки'},
        ),
        migrations.AlterField(
            model_name='lesson',
            name='task',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
