# Generated by Django 3.1.3 on 2022-04-04 21:46

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1_courses', '0014_auto_20220405_0046'),
        ('v1_lessons', '0011_auto_20220404_2307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Урок', 'verbose_name_plural': ('Уроки',)},
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1_courses.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date_posted',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Сортировка'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='task',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Задание'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='theory',
            field=ckeditor.fields.RichTextField(verbose_name='Теория'),
        ),
    ]
