# Generated by Django 3.1.3 on 2022-04-13 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1_lessons', '0012_auto_20220405_0046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
    ]
