# Generated by Django 3.1.3 on 2022-05-17 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1_lessons', '0013_auto_20220413_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='task',
        ),
    ]
