# Generated by Django 3.1.3 on 2022-05-26 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('v1_entrance_questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntranceOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=100, verbose_name='Вариант ответа')),
                ('is_correct', models.BooleanField(null=True, verbose_name='Правильность варианта ответа')),
                ('entrance_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='v1_entrance_questions.entrancequestion', verbose_name='Вопрос из входного тестирования')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
            },
        ),
    ]
