# Generated by Django 3.1.3 on 2022-05-26 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('v1_options', '0001_initial'),
        ('v1_questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='v1_questions.question', verbose_name='Вопрос'),
        ),
    ]
