# Generated by Django 3.1.3 on 2022-05-26 13:53

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('v1_lessons', '0014_remove_lesson_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Вопрос')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1_lessons.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
    ]
