# Generated by Django 3.1.3 on 2022-04-04 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1_certificates', '0002_certificate_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'verbose_name_plural': 'Сертификаты'},
        ),
    ]
