# Generated by Django 3.1.3 on 2022-04-04 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1_courses', '0014_auto_20220405_0046'),
        ('v1_certificates', '0003_auto_20220404_2307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'verbose_name': 'Сертификат', 'verbose_name_plural': ('Сертификаты',)},
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate',
            field=models.FileField(upload_to='certificates/', verbose_name='Сертификат'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1_courses.useroncourse', verbose_name='Слушатель'),
        ),
    ]
