# Generated by Django 3.1.3 on 2022-05-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_certificates', '0006_auto_20220502_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
