# Generated by Django 3.1.3 on 2022-05-26 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('v1_options', '0002_option_question'),
        ('v1_courses', '0021_auto_20220510_2217'),
        ('v1_questions', '0001_initial'),
        ('v1_answer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1_questions.question', verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='answer',
            name='selected_options',
            field=models.ManyToManyField(blank=True, related_name='selected_options', to='v1_options.Option', verbose_name='Выбранные варианты ответа'),
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1_courses.useroncourse', verbose_name='Слушатель'),
        ),
    ]
