# Generated by Django 3.1.3 on 2022-05-26 13:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntranceQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Текст вопроса')),
            ],
            options={
                'verbose_name': 'Вопрос для входного тестирования',
                'verbose_name_plural': 'Вопросы для входного тестирования',
            },
        ),
    ]
