# Generated by Django 3.2.3 on 2022-01-31 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_users', '0002_auto_20211123_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='social_networks',
            field=models.URLField(blank=True, null=True),
        ),
    ]
