# Generated by Django 3.1.3 on 2022-04-04 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1_users', '0004_user_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'Пользователи'},
        ),
    ]
