# Generated by Django 3.1.3 on 2022-04-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_users', '0006_auto_20220405_0046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.IntegerField(blank=True, choices=[(1, 'base'), (2, 'advanced'), (3, 'extra')], default=1, verbose_name='Уровень'),
        ),
    ]
