# Generated by Django 3.1.3 on 2022-05-10 19:17

from django.db import migrations
import v1.apps.v1_users.models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_users', '0010_auto_20220510_1346'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', v1.apps.v1_users.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
    ]
