# Generated by Django 3.1.3 on 2022-05-17 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_users', '0011_auto_20220510_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Подтвержденный аккаунт'),
        ),
    ]
