# Generated by Django 3.1.3 on 2022-05-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_users', '0013_auto_20220519_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.IntegerField(blank=True, choices=[(1, 'base'), (2, 'advanced'), (3, 'extra'), (4, 'test not passed')], default=4, verbose_name='Уровень'),
        ),
    ]
