# Generated by Django 3.1.3 on 2022-05-29 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1_users', '0014_auto_20220526_1832'),
        ('v1_users', '0013_auto_20220521_1924'),
    ]

    operations = [
    ]
