# Generated by Django 3.1.3 on 2022-05-26 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('v1_entrance_options', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('v1_entrance_questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntranceAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.BooleanField(null=True, verbose_name='Правильность ответа')),
                ('entrance_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1_entrance_questions.entrancequestion', verbose_name='Вопрос')),
                ('selected_options', models.ManyToManyField(related_name='selected_options', to='v1_entrance_options.EntranceOption', verbose_name='Выбранные варианты ответа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Слушатель')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
    ]
