# Generated by Django 3.1.3 on 2022-05-26 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('v1_entrance_questions', '0001_initial'),
        ('v1_entrance_answers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entranceanswer',
            name='entrance_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1_entrance_questions.entrancequestion', verbose_name='Вопрос из входного тестирования'),
        ),
        migrations.AlterField(
            model_name='entranceanswer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
